version: "3.8"
services:
    db:
        image: postgres:latest
        container_name: ${APP_NAME}-db
        ports:
            - ${DB_PORT}:5432
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - './docker/postgresql/data/.db-data:/var/lib/postgresql/data/'
        networks:
            - auth-app

    nginx:
        image: nginx:latest
        container_name: ${APP_NAME}-nginx
        ports:
            - ${APP_PORT}:80
        tty: true
        restart: unless-stopped
        volumes:
            - '.:/var/www/auth-app'
            - './docker/nginx/conf.d/:/etc/nginx/conf.d/'
        networks:
            - auth-app

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            target: ${APP_ENV}
        container_name: ${APP_NAME}-php
        restart: unless-stopped
        volumes:
            - './:/var/www/auth-app'
            - './docker/php/ini/local.ini:/usr/local/etc/php/conf.d/local.ini'
            # Для корректной работы tinker внутри контейнера
            - './docker/php/.config/:/var/www/.config/'
        networks:
            - auth-app

networks:
    auth-app:
        driver: bridge
